### ISSUE TITLE
Module 1 Cosmetic Edits

### ISSUE THREAD

**Issue by janezdu** [srush/BT-AI#1]
Line #'s refer to module1.py
- Line 121: Would it be helpful to change the description a little? A personal suggestion:
 > *A dictionary type stores "keys" and "values", and allows you to look up values using their corresponding keys.* You can have as many keys...
- Line 259: Typo, "memerize" should be "memorize"
- Line 298: extra blank line, leads to an extra cell right before the For Loops section
- Lines 353, 370, 180: reformat? I prefer the look of `# * Split` into `# ### Split`
- Lines 447, 459, 478, 498: should `real_word_stringN` be `real_world_string?`

**Comment by srush** [comment]
Fixed thanks.
